[package]
name = "ebpf"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
aya = { git = "https://github.com/aya-rs/aya", rev = "b13070a3429033700f8d13b4f01f81d4ede07fe1", features = [
    "async_tokio",
] }
aya-log = { git = "https://github.com/aya-rs/aya", rev = "b13070a3429033700f8d13b4f01f81d4ede07fe1" }
ebpf-common = { path = "../ebpf-common", features = ["user"] }
anyhow = "1"
env_logger = "0.10"
log = "0.4"
tokio = { version = "1.25", features = [
    "macros",
    "rt",
    "rt-multi-thread",
    "net",
    "signal",
    "time",
] }
clap = { version = "4.1", features = ["derive"] }

[dev-dependencies]
bencher_adapter = { path = "../../../lib/bencher_adapter" }
inventory = "0.3.5"
reqwest = "0.11.17"
serde_json = "1.0"

[[bin]]
name = "ebpf"
path = "src/main.rs"

[[bench]]
name = "xdp"
harness = false
