[package]
name = "get_ts"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
# Workspace
anyhow.workspace = true
clap.workspace = true

[lints]
workspace = true
