[package]
name = "profiler"
version = "0.1.0"
edition = "2021"
publish = false

[features]
dhat-heap = [] 

[dependencies]
aya = "0.12"
aya-log = "0.2"
profiler-common = { path = "../profiler-common", features = ["user"] }
anyhow = "1"
env_logger = "0.10"
libc = "0.2"
log = "0.4"
tokio = { version = "1.25", features = ["macros", "rt", "rt-multi-thread", "net", "signal"] }
chrono = "0.4"
dhat = "0.3"

[dev-dependencies]
criterion = "0.5"

[[bin]]
name = "profiler"
path = "src/main.rs"

[profile.release]
debug = true

[[bench]]
name = "profiler"
harness = false