app = "bencher-api"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = "6s"

[build]
image = "registry.fly.io/bencher-api"

# [[mounts]]
# source = "bencher_data_machines"
# destination = "/var/lib/bencher/data"
# processes = ["app"]

[[services]]
protocol = "tcp"
internal_port = 61016

[[services.ports]]
port = 80
handlers = ["http"]
force_https = true

[[services.ports]]
port = 443
handlers = ["tls", "http"]

[services.concurrency]
type = "connections"
hard_limit = 1024
soft_limit = 1024
