app = "bencher-api-dev"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = "6s"

[build]
image = "registry.fly.io/bencher-api-dev"

[[services]]
protocol = "tcp"
internal_port = 61016
auto_start_machines = false
auto_stop_machines = false
min_machines_running = 1

[[services.ports]]
port = 80
handlers = ["http"]
force_https = true

[[services.ports]]
port = 443
handlers = ["tls", "http"]

[services.concurrency]
type = "connections"
soft_limit = 1024
hard_limit = 1024

[[services.tcp_checks]]
grace_period = "24s"
interval = "12s"
timeout = "2s"
restart_limit = 0

[[services.http_checks]]
grace_period = "24s"
interval = "12s"
timeout = "2s"
method = "get"
path = "/v0/projects?per_page=0"
protocol = "http"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256

[[restart]]
policy = "on-failure"
retries = 6
