[alias]
xtask = "run --manifest-path ./xtask/Cargo.toml --"
xtask-api = "run --manifest-path ./xtask/Cargo.toml --features api --"
xtask-cli = "run --manifest-path ./xtask/Cargo.toml --features cli --"
xtypes = "run --manifest-path ./xtask/Cargo.toml --features api -- types"
xadmin = "run --manifest-path ./xtask/Cargo.toml --features admin --"
# Breakout
gen-installer = "run --manifest-path ./tasks/gen_installer/Cargo.toml --"
gen-pkg = "run --manifest-path ./tasks/gen_pkg/Cargo.toml --"
gen-swagger = "run --manifest-path ./tasks/gen_swagger/Cargo.toml --"
test-netlify = "run --manifest-path ./tasks/test_netlify/Cargo.toml --"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[target.aarch64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]
