[workspace]

[package]
name = "custom"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dev-dependencies]
dhat = "0.3"
inventory = "0.3"
serde_json = "1.0"

[[bench]]
name = "play_game"
harness = false
